config/routes.rb
Rails.application.routes.draw do
  resources :recipes

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:edit, :show, :update]
  def index
    @recipes = Recipe.all
  end

  def show
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to @recipe
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @recipe.update_attributes(recipe_params)
      redirect_to @recipe
    else
      render :edit
    end
  end

  def destroy

  end

  private 
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    def recipe_params
      params.require(:recipe).permit(
        :name,
        :title,
        :serving_size,
        :cook_time,
        :description,
        :ingredients,
        :instructions,
        :image_url
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  = render 'shared/head'
  body
    = render 'shared/header'
    .l-site-inner
      .l-wrap.white-bg
        = yield
    = render 'shared/footer'

app/views/recipes/_form.html.slim
#recipe-form-container
  = form_for @recipe do |f|
    = f.label :name
    = f.text_field :name

    = f.label :title
    = f.text_field :title

    = f.label :serving_size
    = f.text_field :serving_size

    = f.label :cook_time
    = f.text_field :cook_time

    = f.label :description
    = f.text_area :description

    = f.label :ingredients
    = f.text_area :ingredients

    = f.label :instructions
    = f.text_area :instructions

    = f.label :image_url
    = f.text_field :image_url, id: 'image_url'

    p#fp-thumb
    button#fp-clicker Filepicker

    = f.submit

app/views/recipes/edit.html.slim
= render 'form'

app/views/recipes/index.html.slim
main.l-content
  h2 Gallery Content
  ul.m-gallery
    - @recipes.each do |recipe|
      li.m-gallery__item
        = link_to image_tag(recipe.image_url), recipe_path(recipe)
aside.l-sidebar
  h2 Sidebar
  ul
    li
      a href="#" A link to someplace else
    li
      a href="#" A link to someplace else
    li
      a href="#" A link to someplace else
    li
      a href="#" A link to someplace else
    li
      a href="#" A link to someplace else

app/views/recipes/new.html.slim
= render 'form'

app/views/recipes/show.html.slim
- r = @recipe
= image_tag r.image_url
p = r.name
p = r.title
p = r.serving_size
p = r.cook_time
p = simple_format r.description
p = simple_format r.ingredients
p = simple_format r.instructions
p = r.image_url

app/views/shared/_footer.html.slim
footer.l-site-footer
  .l-wrap
    .m-widget
      h2.m-widget__title Widget
    .m-widget
      h2.m-widget__title Widget
    .m-widget
      h2.m-widget__title Widget
    .m-widget
      h2.m-widget__title Widget

app/views/shared/_head.html.slim
head
  title JzoApp
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

app/views/shared/_header.html.slim
header.l-site-header
  .l-wrap
    .l-site-header__logo
      a.l-site-header__link href="#" Logo
    nav.m-nav.float-right
      ul.m-nav__list
        li.m-nav__list-item
          a.m-nav__list-item-link href="#" item01
        li.m-nav__list-item
          a.m-nav__list-item-link href="#" item02
        li.m-nav__list-item
          a.m-nav__list-item-link href="#" item03
        li.m-nav__list-item
          a.m-nav__list-item-link href="#" item04
        li.m-nav__list-item 
          a.m-nav__list-item-link href="#" item05
          .m-nav__content-wrapper 
            ul.m-nav__dropdown-list
              li.m-nav__dropdown-list-item 
                a.m-nav__dropdown-list-item-link awesome